export const ROLES = {
  USER: "USER",
  MECHANIC: "MECHANIC",
  ADMIN: "ADMIN",
};

export const SERVICE_TYPES = [
  "BREAKDOWN_REPAIR",
  "TOWING",
  "BATTERY_JUMPSTART",
  "FLAT_TIRE",
  "FUEL_DELIVERY",
];

export const REQUEST_STATUS = {
  PENDING: "PENDING",
  QUOTED: "QUOTED",
  ACCEPTED: "ACCEPTED",
  ON_THE_WAY: "ON_THE_WAY",
  ARRIVED: "ARRIVED",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

export const MECHANIC_STATUS = {
  ONLINE: "ONLINE",
  OFFLINE: "OFFLINE",
  BUSY: "BUSY",
};